# Generated by Django 3.0.6 on 2020-12-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='desc',
            new_name='Desc',
        ),
    ]
